env:
  - JMETER_VERSION=5.5
  - JMETER_DOCKER_REPO=liukunup/jmeter:${JMETER_VERSION}

services:
  - docker

script:
  - docker build --build-arg JMETER_VERSION=${JMETER_VERSION} -f docker/Dockerfile -t ${JMETER_DOCKER_REPO} .

after_success:
  # 登陆 DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${JMETER_DOCKER_REPO}
  - docker rmi ${JMETER_DOCKER_REPO}
  # 登出 DockerHub
  - docker logout

after_failure:
  - echo "failed"
