apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-web-config
  labels:
    app: node-exporter
data:
  web-config.yml: |
    basic_auth_users:  # 在Linux上输入命令行 htpasswd -nBC 12 '' | tr -d ':\n'
      admin: $2y$12$ngreHCvuz3ySiZKRW13VMuF1w9k/TdFzrno6KcE.aSH6sTGmMNKdK  # 请修改默认密码 perf@JMeter#1024
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        securityContext:
          privileged: true
        args:
        - --web.config.file=/etc/node-exporter/web-config.yml
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
        volumeMounts:
        - name: dev
          mountPath: /host/dev
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: web-config
          mountPath: /etc/node-exporter
          readOnly: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
      - name: web-config
        configMap:
          name: node-exporter-web-config
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
