apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jmeter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jmeter.labels" . | nindent 4 }}
data:
  JVM_ARGS: {{ .Values.javaVirtualMachine }}
