apiVersion: v1
kind: Service
metadata:
  name: {{ include "jmeter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "jmeter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: server-port
      port: 1099
      targetPort: 1099
    - name: local-port
      port: 50000
      targetPort: 50000
  selector:
    {{- include "jmeter.selectorLabels" . | nindent 4 }}
