# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

# Install X11
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    # Install X11
    xvfb xauth \
    $(if [ "$(lsb_release -cs)" = "focal" ]; then echo "x11-apps xorg"; else echo "x11-utils xserver-xorg-core"; fi) && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set DISPLAY environment variable (for X11 forwarding)
ENV DISPLAY=:99

# Keep the container running
ENTRYPOINT ["/entrypoint.sh", "keepalive"]