# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE=liukunup/jmeter:latest
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive \
    VNC_USERNAME="jmeter" \
    VNC_PASSWORD="" \
    DISPLAY=":1"

RUN apt-get update && apt-get install -y \
    sudo openssl \
    # xvfb + xfce + x11vnc + NoVNC
    xvfb \
    # Install XFCE desktop environment
    xfce4 \
    xfce4-goodies \
    x11vnc \
    novnc websockify \
    supervisor \
    # Install DBus for inter-process communication
    dbus-x11 \
    # Install PulseAudio for sound support
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Clean up apt cache to reduce image size
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

COPY jmeter/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 5900 6080

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "vnc" ]
