# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

# Install necessary packages for X11 VNC/NoVNC and RDP
RUN apt update && apt install -y \
    # Install X11
    x11-apps xauth xorg xvfb \
    # Install VNC/NoVNC
    x11vnc novnc websockify \
    # Install RDP
    xrdp xfce4

# Set DISPLAY environment variable (for X11 forwarding)
ENV DISPLAY=host.docker.internal:0

# Expose ports for VNC/NoVNC and RDP
EXPOSE 5900 6080 3389