# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

# Install RDP
RUN apt-get update && \
    apt-get install -y xrdp xfce4 xfce4-goodies && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose port for RDP
EXPOSE 3389

# Start RDP server
ENTRYPOINT ["/entrypoint.sh", "rdp"]