# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

# Install VNC/NoVNC
RUN apt-get update && \
    apt-get install -y xvfb x11vnc novnc websockify && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose ports for VNC and NoVNC
EXPOSE 5900 6080

# Start VNC and NoVNC server
ENTRYPOINT ["/entrypoint.sh", "vnc"]