# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

# Install packages
RUN apt-get update && apt-get install -y \
    # System Requirements
    dbus-x11 \
    sudo \
    nano \
    x11vnc \
    xvfb \
    # Pulse Audio
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Xfce 4
    xfce4 \
    xfce4-goodies \
    xubuntu-icon-theme \
    # Supervisor
    python3 python3-pip supervisor \
    # Ensure git is installed
    git \
    && git clone https://github.com/novnc/noVNC /opt/novnc/noVNC \
    && git clone https://github.com/novnc/websockify /opt/novnc/websockify \
    && ln -s /opt/novnc/noVNC/utils/novnc_proxy /usr/local/bin/novnc_proxy \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY jmeter/supervisord.conf /etc/supervisor/conf.d/vnc.conf

# HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \
#   CMD curl -fsk https://localhost:6080/ || exit 1

EXPOSE 5900 6080

ENTRYPOINT ["/entrypoint.sh", "vnc"]
