# Use the official Alpine Linux image as the base image
ARG BASE_IMAGE_VERSION=latest
FROM alpine:${BASE_IMAGE_VERSION}

# Maintainer
LABEL maintainer="LiuKun<liukunup@outlook.com>"

# Metadata
LABEL org.opencontainers.image.title="JMeter"
LABEL org.opencontainers.image.authors="LiuKun<liukunup@outlook.com>"
LABEL org.opencontainers.image.source="https://github.com/liukunup/JMeter"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.description="Apache JMeter is an open-source software testing tool developed by the Apache Software Foundation.\nJMeter in Docker is a lightweight image that provides a ready-to-use JMeter environment for running performance tests."

# JMeter version & download URL
ARG JMETER_VERSION=5.6.3
ARG JMETER_DOWNLOAD_URL=https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz

# Set environment variables for JMeter
ENV JMETER_HOME=/opt/jmeter
ENV JMETER_BIN=${JMETER_HOME}/bin
ENV JMETER_LIB=${JMETER_HOME}/lib
ENV JMETER_EXT=${JMETER_HOME}/lib/ext
ENV JMETER_LIC=${JMETER_HOME}/licenses

# The folder where custom plugins are stored
ENV JMETER_CUSTOM_PLUGINS_FOLDER=/opt/plugins

# Java Runtime Environment
ARG JRE_VERSION=openjdk21-jre

# Install Python 3 (default: true)
ARG INSTALL_PYTHON_3=true

# Timezone (default: Asia/Shanghai)
ARG TIMEZONE=Asia/Shanghai
ENV TZ=${TIMEZONE}

# Define URLs and versions for various JMeter plugins and drivers
ARG JMETER_PLUGINS_MANAGER_URL=https://jmeter-plugins.org/get/
# jp@gc - Custom Thread Groups
ARG PLUGIN_JPGC_CASUTG_VERSION=2.10
ARG PLUGIN_JPGC_CASUTG_URL=https://jmeter-plugins.org/files/packages/jpgc-casutg-${PLUGIN_JPGC_CASUTG_VERSION}.zip
# jp@gc - PerfMon
ARG PLUGIN_JPGC_PERFMON_VERSION=2.1
ARG PLUGIN_JPGC_PERFMON_URL=https://jmeter-plugins.org/files/packages/jpgc-perfmon-${PLUGIN_JPGC_PERFMON_VERSION}.zip
# InfluxDB v2.8 Listener
ARG PLUGIN_INFLUXDB2_LISTENER_VERSION=2.8
ARG PLUGIN_INFLUXDB2_LISTENER_URL=https://github.com/mderevyankoaqa/jmeter-influxdb2-listener-plugin/releases/download/v${PLUGIN_INFLUXDB2_LISTENER_VERSION}/jmeter-plugins-influxdb2-listener-${PLUGIN_INFLUXDB2_LISTENER_VERSION}.jar
# MySQL Connector-J
ARG DRIVER_MYSQL_CONNECTOR_J_VERSION=9.1.0
ARG DRIVER_MYSQL_CONNECTOR_J_URL=https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-j-${DRIVER_MYSQL_CONNECTOR_J_VERSION}.zip
# WebSocket Samplers
ARG DRIVER_WEBSOCKET_VERSION=1.2.10
ARG DRIVER_WEBSOCKET_URL=https://jmeter-plugins.org/files/packages/websocket-samplers-${DRIVER_WEBSOCKET_VERSION}.zip

# Define the Server Agent version and URL
ARG SERVER_AGENT_VERSION=2.2.3
ARG SERVER_AGENT_URL=https://github.com/undera/perfmon-agent/releases/download/${SERVER_AGENT_VERSION}/ServerAgent-${SERVER_AGENT_VERSION}.zip
# Set the Server Agent home directory
ENV SERVER_AGENT_HOME=/opt/ServerAgent

# Copy the entrypoint script to the root directory
COPY jmeter/entrypoint.sh /

# Install necessary packages
RUN    apk update \
	&& apk upgrade \
	# Add CA certificates and update
	&& apk add ca-certificates \
	&& update-ca-certificates \
	# Install Java, tzdata, curl, bash, vim, tar, unzip, make, net-tools, and nss
	&& apk add --update ${JRE_VERSION} tzdata curl bash vim tar unzip make net-tools \
	&& apk add --no-cache nss \
	# Optionally install Python 3 if INSTALL_PYTHON_3 is true
	&& if [ "$INSTALL_PYTHON_3" = "true" ]; then apk add --update --no-cache python3 py3-pip && ln -sf python3 /usr/bin/python; fi \
	# Clean up APK cache
	&& rm -rf /var/cache/apk/* \
	# Create a temporary directory for dependencies
	&& mkdir -p /tmp/dependencies \
	# Download & Extract JMeter
	&& curl -L --silent ${JMETER_DOWNLOAD_URL} > /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz \
	&& mkdir -p /opt \
	&& tar -zxf /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz -C /opt \
	&& mv /opt/apache-jmeter-${JMETER_VERSION} ${JMETER_HOME} \
	# Make the entrypoint script executable
	&& chmod +x /entrypoint.sh \
	# Clean up temporary dependencies directory
	&& rm -rf /tmp/dependencies

# Install security patch (update vulnerable jar packages)
COPY security /tmp/security/
RUN    chmod +x /tmp/security/patch.sh \
	&& cd /tmp/security \
	&& ./patch.sh \
	&& rm -rf /tmp/security

# Install plugins and drivers
RUN    mkdir -p /tmp/dependencies \
    # Download and unzip jp@gc - Custom Thread Groups
    && curl -L --silent ${PLUGIN_JPGC_CASUTG_URL} > /tmp/dependencies/jpgc-casutg-${PLUGIN_JPGC_CASUTG_VERSION}.zip \
    && unzip /tmp/dependencies/jpgc-casutg-${PLUGIN_JPGC_CASUTG_VERSION}.zip -d ${JMETER_HOME} \
    # Download and unzip jp@gc - PerfMon
    && curl -L --silent ${PLUGIN_JPGC_PERFMON_URL} > /tmp/dependencies/jpgc-perfmon-${PLUGIN_JPGC_PERFMON_VERSION}.zip \
    && unzip /tmp/dependencies/jpgc-perfmon-${PLUGIN_JPGC_PERFMON_VERSION}.zip -d ${JMETER_HOME} \
    # Download InfluxDB v2.8 Listener
    && curl -L --silent ${PLUGIN_INFLUXDB2_LISTENER_URL} > ${JMETER_EXT}/jmeter-plugins-influxdb2-listener-${PLUGIN_INFLUXDB2_LISTENER_VERSION}.jar \
    # Download and unzip MySQL Connector-J
    && curl -L --silent ${DRIVER_MYSQL_CONNECTOR_J_URL} > /tmp/dependencies/mysql-connector-j-${DRIVER_MYSQL_CONNECTOR_J_VERSION}.zip \
    && unzip /tmp/dependencies/mysql-connector-j-${DRIVER_MYSQL_CONNECTOR_J_VERSION}.zip -d ${JMETER_HOME} \
    # Download and unzip WebSocket Samplers
    && curl -L --silent ${DRIVER_WEBSOCKET_URL} > /tmp/dependencies/websocket-samplers-${DRIVER_WEBSOCKET_VERSION}.zip \
    && unzip /tmp/dependencies/websocket-samplers-${DRIVER_WEBSOCKET_VERSION}.zip -d ${JMETER_HOME} \
    # Download JMeter Plugins Manager
    && curl -L --silent ${JMETER_PLUGINS_MANAGER_URL} > ${JMETER_EXT}/jmeter-plugins-manager-latest.jar \
    # Download and unzip Server Agent
    && curl -L --silent ${SERVER_AGENT_URL} > /tmp/dependencies/ServerAgent-${SERVER_AGENT_VERSION}.zip \
    && mkdir -p ${SERVER_AGENT_HOME}  \
    && unzip /tmp/dependencies/ServerAgent-${SERVER_AGENT_VERSION}.zip -d /tmp/dependencies/ \
    && mv /tmp/dependencies/ServerAgent-${SERVER_AGENT_VERSION}/* ${SERVER_AGENT_HOME}/ \
    # Make Server Agent scripts executable
    && chmod +x ${SERVER_AGENT_HOME}/*.sh \
    # Make the entrypoint script executable
    && chmod +x /entrypoint.sh \
    # Clean up temporary files
    && rm -rf /tmp/dependencies

# Add JMeter bin directory to PATH
ENV PATH=${PATH}:${JMETER_BIN}

# Add Server Agent execution path to environment variables
ENV PATH=${PATH}:${SERVER_AGENT_HOME}

# Expose ports for JMeter Server and Mirror Server
EXPOSE 1099 50000 8080

# Set the working directory
WORKDIR ${JMETER_HOME}

# Set the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
