# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE_VERSION=latest
FROM liukunup/jmeter:${BASE_JMETER_IMAGE_VERSION}

ENV DEBIAN_FRONTEND=noninteractive \
    VNC_USERNAME=jmeter \
    VNC_PASSWORD=jmeter \
    DISPLAY=:1

# Install packages
RUN apt-get update && apt-get install -y \
    # PulseAudio
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Xfce 4
    xfce4 \
    xfce4-goodies \
    # Other dependencies
    sudo \
    supervisor \
    x11vnc \
    xvfb \
    novnc \
    websockify \
    openssl \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

COPY jmeter/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 5900 6080

ENTRYPOINT ["/entrypoint.sh", "vnc"]
