# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE=liukunup/jmeter:latest
# hadolint ignore=DL3006
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive \
    NM_USERNAME="jmeter" \
    NM_PASSWORD=""

RUN apt-get update && apt-get install -y \
    sudo openssl \
    # xvfb + xfce
    xvfb \
    # Install XFCE desktop environment
    xfce4 \
    xfce4-goodies \
    # Install DBus for inter-process communication
    dbus-x11 \
    # Install PulseAudio for sound support
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Install and configure NoMachine server
    && curl -fSL "https://www.nomachine.com/free/linux/64/deb" -o nomachine.deb \
    && dpkg -i nomachine.deb \
    && rm -f nomachine.deb \
    && sed -i -e "s|#EnableClipboard both|EnableClipboard both|g" \
    -e "s|#EnableUPnP none|EnableUPnP NXUDP|g" \
    -e "s|#NXUDPPort 4000|NXUDPPort 4000|g" \
    -e "s|#DisplayGeometry .*|DisplayGeometry 1600x900|g" \
    -e "s|#EnableLockScreen 0|EnableLockScreen 1|g" \
    -e "s|#VirtualDesktopAccess administrator,trusted,owner,system|VirtualDesktopAccess administrator,trusted,owner|g" \
    -e "s|#VirtualDesktopAccessNoAcceptance administrator,trusted,owner|VirtualDesktopAccessNoAcceptance administrator,trusted,owner|g" \
    -e "s|#PhysicalDesktopAccess .*|PhysicalDesktopAccess administrator,trusted,owner|g" \
    -e "s|#PhysicalDesktopAccessNoAcceptance .*|PhysicalDesktopAccessNoAcceptance administrator,trusted,owner|g" \
    -e "s|#EnableClientAutoreconnect .*|EnableClientAutoreconnect NX,SSH|g" \
    -e "s|#AcceptedAuthenticationMethods .*|AcceptedAuthenticationMethods NX-private-key|g" \
    /usr/NX/etc/server.cfg \
    # Clean up apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

EXPOSE 4000 4443

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "nomachine" ]
