# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

ENV RDP_PASSWORD=""

# Install RDP
RUN apt-get update && apt-get install -y \
    dbus-x11 \
    sudo \
    nano \
    pavucontrol \
    pulseaudio \
    pulseaudio-utils \
    xfce4 \
    xfce4-terminal \
    xfce4-goodies \
    xfce4-pulseaudio-plugin \
    xrdp xorg xorgxrdp \
    xubuntu-icon-theme \
    software-properties-common \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # Configure xrdp
    && echo "xfce4-session" > /etc/skel/.xsession \
    && echo "startxfce4" > /etc/xrdp/startwm.sh \
    && chmod +x /etc/xrdp/startwm.sh

# Expose port for RDP
EXPOSE 3389/tcp

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "rdp" ]
