# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE=liukunup/jmeter:latest
# hadolint ignore=DL3006
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive \
    NM_USERNAME="jmeter" \
    NM_PASSWORD="" \
    DISPLAY=":0" \
    DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN apt-get update && apt-get install -y \
    sudo openssl \
    # apt-utils vim xterm cups curl \
    #
    xvfb \
    # Install XFCE desktop environment
    xfce4 \
    xfce4-goodies \
    # Install PulseAudio for sound support
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    #
    openssh-server \
    dbus-x11 \
    # && service ssh start \
    # && mkdir -p /var/run/dbus \
    # Install and configure NoMachine server
    && curl -fSL "https://www.nomachine.com/free/linux/64/deb" -o nomachine.deb \
    && dpkg -i nomachine.deb \
    && rm -f nomachine.deb \
    #
    && cp /usr/NX/etc/node.cfg /usr/NX/etc/node.cfg.bak \
    && sed -i \
    -e "s|^DefaultDesktopCommand.*|DefaultDesktopCommand \"/usr/bin/startxfce4\"|" \
    -e "s|^AvailableSessionTypes.*|AvailableSessionTypes unix-remote,unix-console,unix-default,unix-application,physical-desktop,shadow,unix-xsession-default,unix-xdm,SSH|" \
    -e "s|^CommandStartGnome.*|#&|" \
    -e "s|^#DefaultXSession.*|DefaultXSession /usr/bin/startxfce4|" \
    /usr/NX/etc/node.cfg \
    #
    && cp /usr/NX/etc/server.cfg /usr/NX/etc/server.cfg.bak \
    && sed -i \
    -e "s|#EnableClipboard both|EnableClipboard both|g" \
    /usr/NX/etc/server.cfg \
    # && /etc/init.d/dbus start \
    # Clean up apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY jmeter/supervisord-nomachine.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 22 4000

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "nomachine" ]
