[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:Xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1024x768x24
autorestart=true

[program:xfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":0"
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -rfbauth /root/.vnc/passwd
environment=DISPLAY=":0"
autorestart=true

[program:websockify]
command=/usr/bin/websockify --web /opt/noVNC 6080 localhost:5900
autorestart=true

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon
autorestart=true