[supervisord]
nodaemon=true
user=%USERNAME%

[program:xvfb]
command=/usr/bin/Xvfb %DISPLAY% -screen 0 1280x800x24
autostart=true
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display %DISPLAY% -rfbauth /home/%USERNAME%/.vnc/passwd -forever -shared
autostart=true
autorestart=true

[program:startxfce4]
command=/usr/bin/startxfce4
environment=DISPLAY="%DISPLAY%"
autostart=true
autorestart=true

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc 0.0.0.0:5900 --listen 6080 --web /usr/share/novnc --cert /home/%USERNAME%/.certs/vnc.crt --key /home/%USERNAME%/.certs/vnc.key --heartbeat 10 --timeout 300
autostart=true
autorestart=true
