[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x800x24 -ac
autostart=true
autorestart=true
startsecs=3

[program:startxfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":1"
autostart=true
autorestart=true
startsecs=5

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbauth /home/jmeter/.vnc/passwd -noxdamag
autostart=true
autorestart=true
startsecs=5
startretries=10

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc 0.0.0.0:5900 --listen 6080 --web /usr/share/novnc --ssl-only --cert /home/jmeter/.certs/vnc.crt --key /home/jmeter/.certs/vnc.key --heartbeat 10 --timeout 300
autostart=true
autorestart=true
startsecs=10
