[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x800x24
autostart=true
autorestart=true
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb_error.log

[program:startxfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":1"
autostart=true
autorestart=true
stdout_logfile=/var/log/startxfce4.log
stderr_logfile=/var/log/startxfce4_error.log

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared
autostart=true
autorestart=true
stdout_logfile=/var/log/x11vnc.log
stderr_logfile=/var/log/x11vnc_error.log

[program:novnc]
command=novnc
  --vnc 0.0.0.0:5900
  --listen 6080
  --ssl-only
  --cert /opt/certs/vnc.crt
  --key /opt/certs/vnc.key
  --heartbeat 10
  --timeout 300
autostart=true
autorestart=true
stdout_logfile=/var/log/novnc.log
stderr_logfile=/var/log/novnc_error.log
