# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE=liukunup/jmeter:latest
# hadolint ignore=DL3006
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive \
    NM_USERNAME="" \
    NM_PASSWORD="" \
    DISPLAY=":0" \
    RESOLUTION="1280x720" \
    DEPTH="24"

RUN apt-get update && apt-get install -y \
    sudo openssl \
    # Install Xvfb for virtual framebuffer support
    xvfb \
    # Install Xfce desktop environment
    xfce4 \
    xfce4-goodies \
    # Install PulseAudio for sound support
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Install dbus-x11 for X11 forwarding support
    dbus-x11 \
    # [Supervisor: A Process Control System](https://supervisord.org/)
    supervisor \
    # Install NoMachine for remote desktop access
    && curl -fSL "https://www.nomachine.com/free/linux/64/deb" -o nomachine.deb \
    && dpkg -i nomachine.deb \
    && rm -f nomachine.deb \
    # Configure NoMachine - node.cfg
    && cp /usr/NX/etc/node.cfg /usr/NX/etc/node.cfg.bak \
    && sed -i \
    -e "s|^DefaultDesktopCommand.*|DefaultDesktopCommand \"/usr/bin/startxfce4\"|" \
    -e "s|^AvailableSessionTypes.*|AvailableSessionTypes unix-remote,unix-console,unix-default,unix-application,physical-desktop,shadow,unix-xsession-default,unix-xdm|" \
    -e "s|^CommandStartGnome.*|#&|" \
    -e "s|^#DefaultXSession.*|DefaultXSession /usr/bin/startxfce4|" \
    /usr/NX/etc/node.cfg \
    # Configure NoMachine - server.cfg
    && cp /usr/NX/etc/server.cfg /usr/NX/etc/server.cfg.bak \
    && sed -i \
    -e "s|#EnableClipboard both|EnableClipboard both|g" \
    /usr/NX/etc/server.cfg \
    # Clean up apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY docker/supervisord/nomachine.conf /etc/supervisord.conf

EXPOSE 4000

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD [ "nomachine" ]
