# Use the specified JMeter image as the base image
ARG BASE_JMETER_IMAGE=liukunup/jmeter:latest
# hadolint ignore=DL3006
FROM ${BASE_JMETER_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive \
    RDP_USERNAME="" \
    RDP_PASSWORD=""

RUN apt-get update && apt-get install --no-install-recommends -y \
    sudo openssl \
    # Install Xfce desktop environment
    xfce4 \
    xfce4-goodies \
    # Install PulseAudio for sound support
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # Install dbus-x11 for X11 forwarding support
    dbus-x11 \
    # Install xrdp for remote desktop access
    xrdp xorg xorgxrdp \
    # Set the default X session to XFCE for new users by writing to /etc/skel/.xsession
    && echo "xfce4-session" > /etc/skel/.xsession \
    # Change xRDP port to avoid default port conflicts
    && sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini \
    # Configure xRDP to start the XFCE desktop environment by updating /etc/xrdp/startwm.sh
    && echo "startxfce4" > /etc/xrdp/startwm.sh \
    # Ensure /etc/xrdp/startwm.sh is executable so xRDP can launch the session script
    && chmod +x /etc/xrdp/startwm.sh \
    # Clean up apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3390

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD [ "rdp" ]
