version: '3'

services:

  jmeter:
    container_name: jmeter
    image: liukunup/jmeter:5.5
    hostname: jmeter
    command: jmeter -v
    ports:
      - "8888:4444"
    environment:
      - JVM_ARGS="-Xmn256m -Xms512m -Xmx1g -XX:MaxMetaspaceSize=256m"

  jmeter-server:
    container_name: jmeter-server
    image: liukunup/jmeter:5.5
    hostname: jmeter-server
    restart: unless-stopped
    command: jmeter-server

  server-agent:
    container_name: server-agent
    image: liukunup/jmeter:5.5
    hostname: server-agent
    restart: unless-stopped
    command: server-agent
    ports:
      - "8888:4444"
    environment:
      - SA_INTERVAL=10
