# Use the official Alpine Linux image as the base image
ARG BASE_IMAGE_VERSION=latest
FROM alpine:${BASE_IMAGE_VERSION}

# Maintainer
LABEL maintainer="LiuKun<liukunup@outlook.com>"

# Metadata
LABEL org.opencontainers.image.title="JMeter"
LABEL org.opencontainers.image.authors="LiuKun<liukunup@outlook.com>"
LABEL org.opencontainers.image.source="https://github.com/liukunup/JMeter"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.description="Apache JMeter is an open-source software testing tool developed by the Apache Software Foundation.\nJMeter in Docker is a lightweight image that provides a ready-to-use JMeter environment for running performance tests."

# JMeter
ARG JMETER_VERSION=5.6.3
ARG JMETER_DOWNLOAD_URL=https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz

# Set environment variables for JMeter
ENV JMETER_HOME=/opt/jmeter
ENV JMETER_BIN=${JMETER_HOME}/bin
ENV JMETER_LIB=${JMETER_HOME}/lib
ENV JMETER_EXT=${JMETER_HOME}/lib/ext
ENV JMETER_LIC=${JMETER_HOME}/licenses

# The folder where custom plugins are stored
ENV JMETER_CUSTOM_PLUGINS_DIR=/opt/plugins

# Java Runtime Environment
ARG JRE_VERSION=openjdk21-jre

# Install Python 3 (default: true)
ARG INSTALL_PYTHON_3=true

# Timezone (default: Asia/Shanghai)
ARG TIMEZONE=Asia/Shanghai
ENV TZ=${TIMEZONE}

# Add shell scripts
COPY docker/entrypoint.sh docker/logger.sh docker/patch.sh /usr/local/bin/

# Install necessary packages
RUN apk update && apk upgrade --no-cache \
	# Add CA certificates and update
	&& apk add --no-cache ca-certificates \
	&& update-ca-certificates \
	# Install Java, tzdata, curl, bash, vim, nano, tar, unzip, make, net-tools, git and nss
	&& apk add --no-cache ${JRE_VERSION} tzdata curl bash vim nano tar unzip make net-tools git \
	&& apk add --no-cache nss \
	# Optionally install Python 3 if INSTALL_PYTHON_3 is true
	&& if [ "$INSTALL_PYTHON_3" = "true" ]; then \
	  apk add --no-cache python3 py3-pip; \
	  ln -sf python3 /usr/bin/python; \
	fi \
	# Make the entrypoint script executable
	&& chmod +x /usr/local/bin/entrypoint.sh \
	&& chmod +x /usr/local/bin/logger.sh \
	&& chmod +x /usr/local/bin/patch.sh \
    # Clean up apt cache to reduce image size
    && rm -rf /var/cache/apk/*

# Install JMeter
WORKDIR /tmp/dependencies
RUN curl -L --silent ${JMETER_DOWNLOAD_URL} > apache-jmeter-${JMETER_VERSION}.tgz \
	&& mkdir -p /opt \
	&& tar -zxf apache-jmeter-${JMETER_VERSION}.tgz -C /opt \
	&& mv /opt/apache-jmeter-${JMETER_VERSION} ${JMETER_HOME} \
	# Clean up temporary dependencies directory
	&& rm -rf /tmp/dependencies

# Install security patch (update vulnerable jar packages)
WORKDIR /tmp/security
COPY security .
RUN chmod +x patch.sh \
	&& ./patch.sh \
	&& rm -rf /tmp/security

# Run patch script
RUN /usr/local/bin/patch.sh

# Add JMeter bin directory to PATH
ENV PATH=${PATH}:${JMETER_BIN}

# - JMeter Server: 1099, 50000
# - Mirror Server: 8080
EXPOSE 1099 50000 8080

WORKDIR ${JMETER_HOME}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD [ "keepalive" ]
