# 请参考下述链接来了解字段释义
# 中文: https://helm.sh/zh/docs/topics/charts/#Chart-yaml-%e6%96%87%e4%bb%b6

apiVersion: v2

name: jmeter

version: 0.1.0

description: A Helm chart for JMeter

type: application

keywords:
  - JMeter
  - Performance
  - Distribution
  - Test

sources:
  - https://github.com/liukunup/JMeter

maintainers:
  - name: Liu Kun
    email: liukunup@outlook.com
    url: https://github.com/liukunup

icon: https://jmeter.apache.org/images/logo.svg

appVersion: "5.5"
