# 名称覆盖
nameOverride: ""
# 全名覆盖
fullnameOverride: ""


# 副本数量
replicaCount:
  # 工作节点数
  worker: 3
  # 控制节点数
  controller: 1


# 镜像
image:
  repository: liukunup/jmeter
  tag: ""  # 不填情况下将使用`Chart.appVersion`的值
  pullPolicy: IfNotPresent
# 镜像拉取密钥(适用于私有仓库)
imagePullSecrets: []


# JVM
javaVirtualMachine: "-Xmn256m -Xms512m -Xmx1g -XX:MaxMetaspaceSize=256m"


# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""


# 不常用选项
podAnnotations: {}
podSecurityContext: {}
securityContext: {}


# 资源占用&限制
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi


# 水平自动扩缩容
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


# 节点选择器
nodeSelector: {}


# 节点容忍度
tolerations: []


# 节点亲和性
affinity:
  # 工作节点
  worker:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: jmeterMode
                  operator: In
                  values:
                    - worker
            topologyKey: "kubernetes.io/hostname"
  # 控制节点
  controller: {}
