name: build docker images

on:
  push:
    branches:
      - dev/*

env:
  JMETER_VERSION: 5.6.3
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/jmeter

jobs:

  build-push-update:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=raw,value=${{ env.JMETER_VERSION }}
            type=semver,pattern=-{{version}},prefix=${{ env.JMETER_VERSION }}
            type=semver,pattern=-{{major}}.{{minor}}.{{patch}},prefix=${{ env.JMETER_VERSION }}
            type=semver,pattern=-{{major}}.{{minor}},prefix=${{ env.JMETER_VERSION }}
            type=semver,pattern=-{{major}},prefix=${{ env.JMETER_VERSION }},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          file: jmeter/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JMETER_VERSION=${{ env.JMETER_VERSION }}
