name: CI/CD Pipeline for JMeter Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v1.2.3, ...
    paths-ignore:
      - '**.md'
      - '**.jmx'
      - '**.png'
  release:
    types: [ created, edited ]

env:
  JMETER_VERSION: 5.6.3 # The target JMeter version
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/jmeter

jobs:

  build:
    name: Build with OpenJDK 21
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      # 通过tags事件触发，替换掉JMETER_VERSION的值
      - name: Set JMeter version if tag created
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
        run: echo "JMETER_VERSION=${{ github.ref }}" | sed 's/^refs\/tags\/v//' >> $GITHUB_ENV
      # 通过release事件触发，替换掉JMETER_VERSION的值
      - name: Set JMeter version if release created
        if: github.event_name == 'release'
        run: echo "JMETER_VERSION=${{ github.event.release.tag_name }}" | sed 's/^v//' >> $GITHUB_ENV

      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
            registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=${{ env.JMETER_VERSION }},enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          file: jmeter/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ALPINE_VERSION=3
            JAVA_VERSION=openjdk21-jre
            JMETER_VERSION=${{ env.JMETER_VERSION }}

      - name: Extract metadata (tags, labels) for Docker with Plugins
        id: meta-plugins
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
            registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=plugins-${{ env.JMETER_VERSION }},enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=plugins-latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Docker Images with Plugins
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          file: jmeter-with-plugins/Dockerfile
          push: true
          tags: ${{ steps.meta-plugins.outputs.tags }}
          labels: ${{ steps.meta-plugins.outputs.labels }}
          build-args: |
            JMETER_VERSION=${{ env.JMETER_VERSION }}

      - name: Extract metadata (tags, labels) for Docker with Business
        id: meta-business
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
            registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=business-${{ env.JMETER_VERSION }},enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=business-latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Docker Images with Business
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          file: jmeter-with-business/Dockerfile
          push: true
          tags: ${{ steps.meta-business.outputs.tags }}
          labels: ${{ steps.meta-business.outputs.labels }}
          build-args: |
            JMETER_VERSION=${{ env.JMETER_VERSION }}

      - name: Update Docker Hub Repository Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.DOCKER_HUB_REPO }}

  build-openjdk8:
    name: Build with OpenJDK 8
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      # 通过tags事件触发，替换掉JMETER_VERSION的值
      - name: Set JMeter version if tag created
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
        run: echo "JMETER_VERSION=${{ github.ref }}" | sed 's/^refs\/tags\/v//' >> $GITHUB_ENV
      # 通过release事件触发，替换掉JMETER_VERSION的值
      - name: Set JMeter version if release created
        if: github.event_name == 'release'
        run: echo "JMETER_VERSION=${{ github.event.release.tag_name }}" | sed 's/^v//' >> $GITHUB_ENV

      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
            registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=openjdk8-${{ env.JMETER_VERSION }},enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=openjdk8-latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          file: jmeter/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ALPINE_VERSION=3
            JAVA_VERSION=openjdk8-jre
            JMETER_VERSION=${{ env.JMETER_VERSION }}

      - name: Extract metadata (tags, labels) for Docker with Plugins
        id: meta-plugins
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_REPO }}
            ghcr.io/${{ github.repository }}
            registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_HUB_REPO }}
          tags: |
            type=raw,value=openjdk8-plugins-${{ env.JMETER_VERSION }},enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=openjdk8-plugins-latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push Docker Images with Plugins
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          file: jmeter-with-plugins/Dockerfile
          push: true
          tags: ${{ steps.meta-plugins.outputs.tags }}
          labels: ${{ steps.meta-plugins.outputs.labels }}
          build-args: |
            JMETER_VERSION=openjdk8-${{ env.JMETER_VERSION }}
