name: JMeter Docker Images CI/CD

on:
  push:
    branches:
      - dev
      - feature/*
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
      - 'LICENSE'
      - 'deploy/**'
      - 'docs/**'
      - 'helm-charts/**'
      - 'scripts/**'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
      - 'LICENSE'
      - 'deploy/**'
      - 'docs/**'
      - 'helm-charts/**'
      - 'scripts/**'

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/jmeter

jobs:
  # Ubuntu
  build-ubuntu-jmeter-images:
    name: Build JMeter images based on Ubuntu
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:  # format: {jmeter}-{os}-{version}-{jre}
        jmeter: ["5.6.3"]
        jre: ["openjdk-21-jre"]
        version: ["24.04"]
        os: ["ubuntu"]
        include:
          - dockerfile: "jmeter/Dockerfile.Ubuntu"
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-
          labels: |
            org.opencontainers.image.title=JMeter
            org.opencontainers.image.description=Apache JMeter Docker image based on ${{ matrix.os }}:${{ matrix.version }} with ${{ matrix.jre }}
            org.opencontainers.image.version=${{ matrix.jmeter }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE_VERSION=${{ matrix.version }}
            JMETER_VERSION=${{ matrix.jmeter }}
            JRE_VERSION=${{ matrix.jre }}

  build-ubuntu-jmeter-images-with-plugins:
    name: Build JMeter images based on Ubuntu with Plugins
    needs: build-ubuntu-jmeter-images
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:  # format: {jmeter}-{os}-{version}-{jre}-plugins
        jmeter: ["5.6.3"]
        jre: ["openjdk-21-jre"]
        version: ["24.04"]
        os: ["ubuntu"]
        include:
          - dockerfile: "jmeter/Dockerfile.Plugins"
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-plugins-
          labels: |
            org.opencontainers.image.title=JMeter with Plugins
            org.opencontainers.image.description=Apache JMeter Docker image based on ${{ matrix.os }}:${{ matrix.version }} with ${{ matrix.jre }}, including additional plugins
            org.opencontainers.image.version=${{ matrix.jmeter }}

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_JMETER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-${{ steps.get_short_sha.outputs.SHORT_SHA }}

  build-ubuntu-jmeter-images-with-gui:
    name: Build JMeter images based on Ubuntu with Desktop
    needs: build-ubuntu-jmeter-images-with-plugins
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:  # format: {jmeter}-{os}-{version}-{jre}-{gui}
        include:
          - dockerfile: "jmeter/Dockerfile.Ubuntu-with-VNC"
            jmeter: "5.6.3"
            jre: "openjdk-21-jre"
            os: "ubuntu"
            version: "24.04"
            gui: "vnc"
          - dockerfile: "jmeter/Dockerfile.Ubuntu-with-RDP"
            jmeter: "5.6.3"
            jre: "openjdk-21-jre"
            os: "ubuntu"
            version: "24.04"
            gui: "rdp"
          - dockerfile: "jmeter/Dockerfile.Ubuntu-with-NoMachine"
            jmeter: "5.6.3"
            jre: "openjdk-21-jre"
            os: "ubuntu"
            version: "24.04"
            gui: "nomachine"
          - dockerfile: "jmeter/Dockerfile.Ubuntu-FullStack"
            jmeter: "5.6.3"
            jre: "openjdk-21-jre"
            os: "ubuntu"
            version: "24.04"
            gui: "fullstack"
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-${{ matrix.gui }}-
          labels: |
            org.opencontainers.image.title=JMeter with GUI
            org.opencontainers.image.description=Apache JMeter Docker image based on ${{ matrix.os }}:${{ matrix.version }} with ${{ matrix.jre }}, including GUI support for ${{ matrix.gui }}
            org.opencontainers.image.version=${{ matrix.jmeter }}

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_JMETER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-plugins-${{ steps.get_short_sha.outputs.SHORT_SHA }}

  build-ubuntu-jmeter-images-with-business:
    name: Build JMeter images based on Ubuntu with Business
    needs: build-ubuntu-jmeter-images-with-plugins
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:  # format: {jmeter}-{os}-{version}-{jre}-business
        jmeter: ["5.6.3"]
        jre: ["openjdk-21-jre"]
        version: ["24.04"]
        os: ["ubuntu"]
        include:
          - dockerfile: "jmeter/Dockerfile.Business"
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=sha,format=short,prefix=${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-business-
          labels: |
            org.opencontainers.image.title=JMeter with Business
            org.opencontainers.image.description=Apache JMeter Docker image based on ${{ matrix.os }}:${{ matrix.version }} with ${{ matrix.jre }}, including additional business
            org.opencontainers.image.version=${{ matrix.jmeter }}

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_JMETER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ matrix.jmeter }}-${{ matrix.os }}-${{ matrix.version }}-${{ matrix.jre }}-plugins-${{ steps.get_short_sha.outputs.SHORT_SHA }}
