name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'releases/**'

env:
  JMETER_VERSION: 5.5
  JMETER_DOCKER_REPO: liukunup/jmeter:$JMETER_VERSION

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: DockerHub login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push & Clean
      run: |
        echo "JMeter Version: $JMETER_VERSION"
        echo "Docker Image Tag: $JMETER_DOCKER_REPO"
        docker build --build-arg JMETER_VERSION=$JMETER_VERSION -f docker/Dockerfile -t $JMETER_DOCKER_REPO .
        docker push $JMETER_DOCKER_REPO
        docker rmi $JMETER_DOCKER_REPO

    - name: DockerHub login
      run: docker logout
