name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'releases/**'

env:
  JMETER_VERSION: 5.5
  DOCKER_HUB_REPO: liukunup/jmeter

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: $DOCKER_HUB_REPO

    - name: Build & Push Docker image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "JMETER_VERSION=$JMETER_VERSION"
